package main.stat;

public enum StatisticType {
    NUM_PIT_DEATHS,
    MAX_LEVEL_CONQUERED,
    NUM_ENEMIES_KILLED,
    NUM_BOSS_KILLED,
    NUM_STARS_COLLECTED,
    NUM_TREASURES_COLLECTED,
    NUM_BOULDERS_BOMBED,
    NUM_ENEMIES_KILLED_WITH_BOMB,
    NUM_ENEMIES_KILLED_WITH_ARROW,
    NUM_ENEMIES_KILLED_WHEN_INVICIBLE,
    NUM_DOORS_UNLOCKED
}
